-- MariaDB schema for DialerHub
CREATE TABLE IF NOT EXISTS Agents (
  AgentId VARCHAR(100) PRIMARY KEY,
  MachineName VARCHAR(255) NOT NULL,
  IPs TEXT NULL,
  MACs TEXT NULL,
  Version VARCHAR(50) NULL,
  LastSeenUtc DATETIME NOT NULL,
  Status VARCHAR(32) NOT NULL,
  InstanceId VARCHAR(100) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Commands (
  Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  AgentId VARCHAR(100) NOT NULL,
  Type VARCHAR(50) NOT NULL,
  Payload TEXT NULL,
  Status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  ClaimedByInstance VARCHAR(100) NULL,
  CreatedAtUtc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAtUtc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX IX_Commands_Status (Status),
  INDEX IX_Commands_Agent (AgentId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
